[package]
authors = ["Michal Atlas <michal.z.atlas@gmail.com>"]
edition = "2018"
name = "mate"
version = "3.0.0"

[dependencies]
ansi_term = "0.12.1"
tokio = { version = "1", features = ["full"] }
clap = { version = "2.33", features = ["yaml"] }
